export const ScreenNames = {
  Splash: 'Splash',
  Register: 'Register',
  Login: 'Login',
  Home: 'Home',
  ProductDetails: 'ProductDetails',
  BottomTab: 'BottomTab',
  Profile: 'Profile',
  Wishlist: 'Wishlist',
  Orders: 'Orders',
  Cart: 'Cart',
  TermsAndCondition: 'TermsAndCondition',
  Notifications: 'Notifications',
  Payment: 'Payment',
  AddCard: 'AddCard',
  Addresses: 'Addresses',
  AddAddress: 'AddAddress',
  ManagePayment: 'ManagePayment',
  AddMoneyToWallet: 'AddMoneyToWallet',
  OrderDetails: 'OrderDetails',
  Reviews: 'Reviews',
};
